//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektDotNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nalozi
    {
        public System.Guid nalogID { get; set; }
        public string vrsta_kvara { get; set; }
        public string prijavio { get; set; }
        public string odjel { get; set; }
        public System.DateTime datum { get; set; }
        public string inv_br { get; set; }
        public string marka { get; set; }
        public string status { get; set; }
        public string opis { get; set; }
    }
}
